version: "3"
services:
    rtsim-test-db:
        image: postgres:latest
        restart: always
        container_name: rtsim-test-db
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "rtsim-test"
            POSTGRES_PASSWORD: "123456"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - 15432:5432

volumes:
    postgres-data:
